### ISSUE TITLE
Add help flag

### ISSUE THREAD

**Issue by BDadmehr0** [BDadmehr0/PFinder#1]
Add the help flag to the program and when the flag is used, it will display the necessary explanations and how to use the script.

**Comment by Elock98** [comment]
Did you mean that when you run:
```
$ python3 main.py -h
```
it should print out help information like usage and available options?

**Comment by BDadmehr0** [comment]
Yes, that's correct. When the user uses the '-h' flag, the program will print an explanation about its functionality and how it works.

**Comment by Elock98** [comment]
It looks like you are using argparse and it comes with a help-flag builtin, so it should already work as you described it. Have you tried running the code with the `-h` flag?

**Comment by BDadmehr0** [comment]
I hadn't tried it before, but it seems that it already has the -h flag built-in.

**Comment by BDadmehr0** [comment]
Thank you for your help

> It looks like you are using argparse and it comes with a help-flag builtin, so it should already work as you described it. Have you tried running the code with the `-h` flag?

Thank you for your help

**Comment by Elock98** [comment]
No problem, glad I could help!
